# Generated by Django 5.2.7 on 2026-05-02 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_participantsubmission_info_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccommodationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Accommodation Info",
            },
        ),
        migrations.CreateModel(
            name="AccommodationOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("url", models.URLField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="accommodation/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="core.accommodationinfo",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
