# Generated by Django 6.0.5 on 2026-10-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_conferenceinfo_venue_map_embed_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="React",
        ),
    ]
