# Generated by Django 5.2.17 on 2026-10-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_conference"),
    ]

    operations = [
        migrations.AddField(
            model_name="conferenceinfo",
            name="registration_opening",
            field=models.DateField(blank=True, null=True),
        ),
    ]
