# Generated by Django 5.2.17 on 2026-10-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_registration_opening"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conferenceinfo",
            name="info_desk_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="conferenceinfo",
            name="venue_map_embed_url",
            field=models.TextField(
                blank=True,
                default="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1280.3159498589002!2d14.416798000000002!3d50.074455!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x470b94f4244a8a5f%3A0xcd7ab24cf4bcbdc7!2sTrojanova%20339%2F13%2C%20120%2000%20Nov%C3%A9%20M%C4%9Bsto%2C%20Czechia!5e0!3m2!1sen!2sus!4v1791310756815!5m2!1sen!2sus",
            ),
        ),
        migrations.AlterField(
            model_name="conferenceinfo",
            name="venue_text",
            field=models.TextField(
                blank=True,
                default="Faculty of Nuclear Sciences and Physical Engineering, Trojanova 13, 120 00, Prague",
            ),
        ),
    ]
