# Generated by Django 5.2.17 on 2026-10-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_conferenceinfo_venue_map_embed_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conferenceinfo",
            name="program_text",
            field=models.TextField(blank=True, default="The program is not ready yet."),
        ),
    ]
