# Generated by Django 5.2.17 on 2026-10-06 18:28

from django.db import migrations


def merge_program_texts(apps, schema_editor):
    """Fold the three section texts into the single markdown field.

    Each non-empty section becomes a "## <heading>" block in the order
    the public program page showed them, so no stored text is lost.
    """
    ConferenceInfo = apps.get_model("core", "ConferenceInfo")
    sections = (
        ("program_local_registration_text", "Registration for local participants"),
        ("program_regular_talks_text", "Regular talks"),
        ("program_poster_talks_text", "Poster pitch talks"),
    )
    for info in ConferenceInfo.objects.all():
        blocks = [
            f"## {heading}\n\n{value.strip()}"
            for field, heading in sections
            if (value := getattr(info, field).strip())
        ]
        if blocks:
            info.program_text = "\n\n".join(blocks)
            info.save(update_fields=["program_text"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_conferenceinfo_program_text_and_more"),
    ]

    operations = [
        migrations.RunPython(merge_program_texts, migrations.RunPython.noop),
    ]
