# Generated by Django 5.2.17 on 2026-10-06 18:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_merge_program_texts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conferenceinfo",
            name="program_local_registration_text",
        ),
        migrations.RemoveField(
            model_name="conferenceinfo",
            name="program_poster_talks_text",
        ),
        migrations.RemoveField(
            model_name="conferenceinfo",
            name="program_regular_talks_text",
        ),
    ]
