# Generated by Django 5.2.17 on 2026-10-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_remove_conferenceinfo_program_local_registration_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conferenceinfo",
            name="program_text",
            field=models.TextField(blank=True),
        ),
    ]
