# Generated by Django 5.2.17 on 2026-10-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_submission_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="conferenceinfo",
            name="submission_edit_deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
